// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/filter_preferences_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2837796297966792825),
    name: 'FilterPreferencesEntity',
    lastPropertyId: const obx_int.IdUid(9, 131758889587927402),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4603631791238697926),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1120255512092504556),
        name: 'year',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3950795987311073520),
        name: 'season',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4983824724505441837),
        name: 'district',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5363197189638499710),
        name: 'taluka',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5331669542980312570),
        name: 'village',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8031752054661184895),
        name: 'dateRangeStartMillis',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6406486354155238962),
        name: 'dateRangeEndMillis',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 131758889587927402),
        name: 'statusesCsv',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 2837796297966792825),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FilterPreferencesEntity: obx_int.EntityDefinition<FilterPreferencesEntity>(
      model: _entities[0],
      toOneRelations: (FilterPreferencesEntity object) => [],
      toManyRelations: (FilterPreferencesEntity object) => {},
      getId: (FilterPreferencesEntity object) => object.id,
      setId: (FilterPreferencesEntity object, int id) {
        object.id = id;
      },
      objectToFB: (FilterPreferencesEntity object, fb.Builder fbb) {
        final yearOffset = object.year == null
            ? null
            : fbb.writeString(object.year!);
        final seasonOffset = object.season == null
            ? null
            : fbb.writeString(object.season!);
        final districtOffset = object.district == null
            ? null
            : fbb.writeString(object.district!);
        final talukaOffset = object.taluka == null
            ? null
            : fbb.writeString(object.taluka!);
        final villageOffset = object.village == null
            ? null
            : fbb.writeString(object.village!);
        final statusesCsvOffset = fbb.writeString(object.statusesCsv);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, yearOffset);
        fbb.addOffset(2, seasonOffset);
        fbb.addOffset(3, districtOffset);
        fbb.addOffset(4, talukaOffset);
        fbb.addOffset(5, villageOffset);
        fbb.addInt64(6, object.dateRangeStartMillis);
        fbb.addInt64(7, object.dateRangeEndMillis);
        fbb.addOffset(8, statusesCsvOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final yearParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final seasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final districtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final talukaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final villageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final dateRangeStartMillisParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 16);
        final dateRangeEndMillisParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 18);
        final statusesCsvParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final object = FilterPreferencesEntity(
          id: idParam,
          year: yearParam,
          season: seasonParam,
          district: districtParam,
          taluka: talukaParam,
          village: villageParam,
          dateRangeStartMillis: dateRangeStartMillisParam,
          dateRangeEndMillis: dateRangeEndMillisParam,
          statusesCsv: statusesCsvParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FilterPreferencesEntity] entity fields to define ObjectBox queries.
class FilterPreferencesEntity_ {
  /// See [FilterPreferencesEntity.id].
  static final id = obx.QueryIntegerProperty<FilterPreferencesEntity>(
    _entities[0].properties[0],
  );

  /// See [FilterPreferencesEntity.year].
  static final year = obx.QueryStringProperty<FilterPreferencesEntity>(
    _entities[0].properties[1],
  );

  /// See [FilterPreferencesEntity.season].
  static final season = obx.QueryStringProperty<FilterPreferencesEntity>(
    _entities[0].properties[2],
  );

  /// See [FilterPreferencesEntity.district].
  static final district = obx.QueryStringProperty<FilterPreferencesEntity>(
    _entities[0].properties[3],
  );

  /// See [FilterPreferencesEntity.taluka].
  static final taluka = obx.QueryStringProperty<FilterPreferencesEntity>(
    _entities[0].properties[4],
  );

  /// See [FilterPreferencesEntity.village].
  static final village = obx.QueryStringProperty<FilterPreferencesEntity>(
    _entities[0].properties[5],
  );

  /// See [FilterPreferencesEntity.dateRangeStartMillis].
  static final dateRangeStartMillis =
      obx.QueryIntegerProperty<FilterPreferencesEntity>(
        _entities[0].properties[6],
      );

  /// See [FilterPreferencesEntity.dateRangeEndMillis].
  static final dateRangeEndMillis =
      obx.QueryIntegerProperty<FilterPreferencesEntity>(
        _entities[0].properties[7],
      );

  /// See [FilterPreferencesEntity.statusesCsv].
  static final statusesCsv = obx.QueryStringProperty<FilterPreferencesEntity>(
    _entities[0].properties[8],
  );
}
